//Maya Preference 2017 (Release 1)
//
//
filePathEditor -registerType "MASH_Audio.filename" -typeLabel "MASH Audio" ;
filePathEditor -registerType "audio.filename" -typeLabel "Audio" ;
filePathEditor -registerType "file" -typeLabel "Texture" ;
filePathEditor -registerType "imagePlane.imageName" -typeLabel "Image Plane" ;
filePathEditor -registerType "reference" -typeLabel "Reference" ;
filePathEditor -registerType "svgToPoly.svgFilepath" -typeLabel "SVG" ;
